import React, { createContext, useContext, useEffect, useState, useMemo } from "react";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";

type Language = "PL" | "EN";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  EN: {
    "nav.bookings": "Bookings",
    "nav.calendar": "Calendar",
    "nav.pricing": "Pricing",
    "nav.transfers": "Transfers",
    "nav.operations": "Operations",
    "nav.analytics": "Analytics",
    "nav.signout": "Sign out",
    "nav.today": "Today",
    "nav.cleaning": "Cleaning",
    "nav.table": "Table",
    "nav.language": "Language",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.loading": "Loading...",
    "calendar.month": "Month",
    "calendar.year": "Year",
    "cleaning.staff": "Staff",
    "cleaning.date": "Cleaning Date",
    "cleaning.property": "Property",
    "cleaning.guest": "Guest",
    "cleaning.arrival": "Arrival",
    "cleaning.departure": "Departure",
    "cleaning.people": "People",
    "cleaning.no_bookings": "No bookings for this property this month.",
    "cleaning.all_day": "All day",
    "cleaning.from": "from",
    "cleaning.to": "to",
    "cleaning.select_date": "Select date",
    "dashboard.title": "Bookings",
    "dashboard.subtitle": "Manage your property reservations across all channels",
    "dashboard.analytics": "Analytics & Trends",
    "dashboard.turnover": "Turnover",
    "dashboard.host_revenue": "Host Revenue",
    "dashboard.total_price": "Total Price",
    "dashboard.commission": "Commission",
    "dashboard.bookings_count": "Bookings Count",
    "dashboard.month": "Month",
    "dashboard.total": "Total",
    "dashboard.no_data": "No data found for the selected period.",
    "dashboard.check_email": "Check email",
    "dashboard.check_ical": "Check iCal",
    "dashboard.new_booking": "New Booking",
    "dashboard.no_bookings": "No bookings found matching your filters.",
    "dashboard.total_revenue": "Total Revenue",
    "dashboard.confirmed_bookings": "Confirmed Bookings",
    "dashboard.pending_deposits": "Pending Deposits",
    "dashboard.avg_nightly": "Avg. Nightly",
    "dashboard.avg_booking_price": "Avg. Booking Price",
    "dashboard.avg_nightly_price": "Avg. Nightly Price",
    "dashboard.booked_weekends_past": "Booked Weekends (YTD)",
    "dashboard.booked_weekends_3m": "Booked Weekends (3m)",
    "dashboard.booked_weekends_6m": "Booked Weekends (6m)",
    "dashboard.profit": "Profit",
    "dashboard.summary": "Summary",
    "dashboard.profit_desc": "Total Price - Commission - Cleaning",
    "dashboard.cashflow": "Cashflow (in)",
    "dashboard.free_cashflow": "Free Cashflow",
    "dashboard.cash_in": "Cash Received",
    "dashboard.cleaning_prev": "Cleaning (prev. month)",
    "dashboard.transfers_count": "Transfers",
    "dashboard.cashflow_desc": "Bank transfers by the date money arrived, not by check-in. Starts May 2026, when transfers began being recorded.",
    "dashboard.free_cashflow_desc": "Cash received minus cash out that month: utilities and purchases by payment date, plus the previous month's cleaning. Starts May 2026.",
    "dashboard.cleaning_costs": "Cleaning Costs",
    "dashboard.utility_costs": "Utility Costs",
    "dashboard.purchase_costs": "Purchase Costs",
    "dashboard.extra_cleaning": "Extra cleaning",
    "operations.expenses": "Expenses",
    "operations.add_utility": "Add Utility Bill",
    "operations.add_purchase": "Add Purchase",
    "operations.bill_period": "Bill Period",
    "operations.payment_date": "Payment Date",
    "operations.category": "Category",
    "operations.amount": "Amount",
    "operations.utility_type": "Utility Type",
    "operations.power": "Power / Electricity",
    "operations.gas": "Gas",
    "operations.water": "Water",
    "operations.other": "Other",
    "operations.purchase_item": "Purchase Item",
    "operations.expense_deleted": "Expense deleted",
    "operations.expense_added": "Expense added",
    "operations.expense_updated": "Expense updated",
    "operations.edit_utility": "Edit Utility Bill",
    "operations.edit_purchase": "Edit Purchase",
    "dashboard.filter_all": "All",
    "dashboard.filter_all_properties": "All Properties",
    "dashboard.filter_all_channels": "All Channels",
    "dashboard.filter_property": "Property",
    "dashboard.filter_channel": "Channel",
    "dashboard.filter_status": "Status",
    "dashboard.filter_active": "Active",
    "dashboard.filter_time": "Time Range",
    "dashboard.filter_this_month": "This Month",
    "dashboard.filter_next_month": "Next Month",
    "dashboard.filter_3months": "Next 3 Months",
    "dashboard.filter_6months": "Next 6 Months",
    "transfers.title": "Transfer Matching",
    "transfers.subtitle": "Manually match incoming bank transfers to bookings",
    "transfers.pending": "Pending Transfers",
    "transfers.matched": "Matched Transfers",
    "transfers.no_pending": "No pending transfers found.",
    "transfers.no_matched": "No matched transfers found.",
    "transfers.booking": "Booking",
    "transfers.sender": "Sender",
    "transfers.title_column": "Title",
    "transfers.amount": "Amount",
    "transfers.date": "Date",
    "transfers.find_matches": "Find Matches",
    "transfers.ignore": "Irrelevant",
    "transfers.matching_for": "Matching for",
    "transfers.close_matches": "Closest Matches",
    "transfers.score": "Score",
    "transfers.select": "Select",
    "transfers.no_matches": "No close matches found. Please search for a booking manually.",
    "transfers.success_match": "Transfer matched successfully",
    "transfers.success_ignore": "Transfer marked as irrelevant",
    "transfers.matched_status": "Matched",
    "transfers.reassign": "Reassign",
    "common.night": "night",
    "common.nights": "nights",
    "common.error": "Error",
    "common.success": "Success",
    "common.saved": "Saved",
    "calendar.view_cleaning": "Cleaning View",
    "calendar.cleaning_time": "Time for cleaning and maintenance",
    "calendar.guests_short": "guests",
    "calendar.animals_short": "pets",
    "calendar.occupied": "Occupied",
    "alert.double_booking": "Double-Booking Detected",
    "alert.double_booking_desc": "There are overlapping bookings on the same property. Please review the following conflicts:",
  },
  PL: {
    "nav.bookings": "Rezerwacje",
    "nav.calendar": "Kalendarz",
    "nav.pricing": "Cennik",
    "nav.transfers": "Przelewy",
    "nav.operations": "Operacje",
    "nav.analytics": "Analityka",
    "nav.signout": "Wyloguj",
    "nav.today": "Dzisiaj",
    "nav.cleaning": "Sprzątanie",
    "nav.table": "Tabelka",
    "nav.language": "Język",
    "common.save": "Zapisz",
    "common.cancel": "Anuluj",
    "common.loading": "Ładowanie...",
    "calendar.month": "Miesiąc",
    "calendar.year": "Rok",
    "cleaning.staff": "Sprzątająca",
    "cleaning.date": "Dzień sprzątania",
    "cleaning.property": "Obiekt",
    "cleaning.guest": "Gość",
    "cleaning.arrival": "Przyjazd",
    "cleaning.departure": "Wyjazd",
    "cleaning.people": "Osób",
    "cleaning.no_bookings": "Brak rezerwacji dla tego obiektu w tym miesiącu.",
    "cleaning.all_day": "Cały dzień",
    "cleaning.from": "od",
    "cleaning.to": "do",
    "cleaning.select_date": "Wybierz datę",
    "dashboard.title": "Rezerwacje",
    "dashboard.subtitle": "Zarządzaj rezerwacjami ze wszystkich kanałów",
    "dashboard.analytics": "Analityka i Trendy",
    "dashboard.turnover": "Obrót",
    "dashboard.host_revenue": "Przychód Gospodarza",
    "dashboard.total_price": "Cena Całkowita",
    "dashboard.commission": "Prowizja",
    "dashboard.bookings_count": "Liczba rezerwacji",
    "dashboard.month": "Miesiąc",
    "dashboard.total": "Suma",
    "dashboard.no_data": "Brak danych dla wybranego okresu.",
    "dashboard.check_email": "Sprawdź e-mail",
    "dashboard.check_ical": "Sprawdź iCal",
    "dashboard.new_booking": "Nowa rezerwacja",
    "dashboard.no_bookings": "Nie znaleziono rezerwacji pasujących do filtrów.",
    "dashboard.total_revenue": "Przychód całkowity",
    "dashboard.confirmed_bookings": "Potwierdzone rezerwacje",
    "dashboard.pending_deposits": "Oczekujące kaucje",
    "dashboard.avg_nightly": "Średnia za noc",
    "dashboard.avg_booking_price": "Średnia rezerwacja",
    "dashboard.avg_nightly_price": "Średnia cena nocy",
    "dashboard.booked_weekends_past": "Zajęte weekendy (rok)",
    "dashboard.booked_weekends_3m": "Zajęte weekendy (3m)",
    "dashboard.booked_weekends_6m": "Zajęte weekendy (6m)",
    "dashboard.profit": "Zysk",
    "dashboard.summary": "Podsumowanie",
    "dashboard.profit_desc": "Cena Całkowita - Prowizja - Sprzątanie",
    "dashboard.cashflow": "Przepływy (wpływy)",
    "dashboard.free_cashflow": "Wolne przepływy",
    "dashboard.cash_in": "Wpływy",
    "dashboard.cleaning_prev": "Sprzątanie (poprz. mies.)",
    "dashboard.transfers_count": "Przelewy",
    "dashboard.cashflow_desc": "Przelewy bankowe wg daty wpływu, nie wg daty zameldowania. Od maja 2026, kiedy zaczęliśmy rejestrować przelewy.",
    "dashboard.free_cashflow_desc": "Wpływy minus wydatki w danym miesiącu: media i zakupy wg daty płatności oraz sprzątanie z poprzedniego miesiąca. Od maja 2026.",
    "dashboard.cleaning_costs": "Koszty sprzątania",
    "dashboard.utility_costs": "Media",
    "dashboard.purchase_costs": "Zakupy",
    "dashboard.extra_cleaning": "Extra sprzątanie",
    "operations.expenses": "Koszty",
    "operations.add_utility": "Dodaj Rachunek",
    "operations.add_purchase": "Dodaj Zakup",
    "operations.bill_period": "Okres",
    "operations.payment_date": "Data płatności",
    "operations.category": "Kategoria",
    "operations.amount": "Kwota",
    "operations.utility_type": "Rodzaj mediów",
    "operations.power": "Prąd / Elektryczność",
    "operations.gas": "Gaz",
    "operations.water": "Woda",
    "operations.other": "Inne",
    "operations.purchase_item": "Co kupiono",
    "operations.expense_deleted": "Koszt usunięty",
    "operations.expense_added": "Koszt dodany",
    "operations.expense_updated": "Koszt zaktualizowany",
    "operations.edit_utility": "Edytuj Rachunek",
    "operations.edit_purchase": "Edytuj Zakup",
    "dashboard.filter_all": "Wszystkie",
    "dashboard.filter_all_properties": "Wszystkie Obiekty",
    "dashboard.filter_all_channels": "Wszystkie Kanały",
    "dashboard.filter_property": "Obiekt",
    "dashboard.filter_channel": "Kanał",
    "dashboard.filter_status": "Status",
    "dashboard.filter_active": "Aktywne",
    "dashboard.filter_time": "Zakres czasu",
    "dashboard.filter_this_month": "Ten miesiąc",
    "dashboard.filter_next_month": "Następny miesiąc",
    "dashboard.filter_3months": "Następne 3 miesiące",
    "dashboard.filter_6months": "Następne 6 miesięcy",
    "transfers.title": "Dopasowanie przelewów",
    "transfers.subtitle": "Ręcznie dopasuj przychodzące przelewy bankowe do rezerwacji",
    "transfers.pending": "Oczekujące przelewy",
    "transfers.matched": "Dopasowane przelewy",
    "transfers.no_pending": "Nie znaleziono oczekujących przelewów.",
    "transfers.no_matched": "Nie znaleziono dopasowanych przelewów.",
    "transfers.booking": "Rezerwacja",
    "transfers.sender": "Nadawca",
    "transfers.title_column": "Tytuł",
    "transfers.amount": "Kwota",
    "transfers.date": "Data",
    "transfers.find_matches": "Znajdź dopasowania",
    "transfers.ignore": "Nieistotny",
    "transfers.matching_for": "Dopasowanie dla",
    "transfers.close_matches": "Najbliższe dopasowania",
    "transfers.score": "Wynik",
    "transfers.select": "Wybierz",
    "transfers.no_matches": "Nie znaleziono bliskich dopasowań. Proszę wyszukaj rezerwację ręcznie.",
    "transfers.success_match": "Przelew dopasowany pomyślnie",
    "transfers.success_ignore": "Przelew oznaczony jako nieistotny",
    "transfers.matched_status": "Dopasowano",
    "transfers.reassign": "Zmień dopasowanie",
    "common.night": "noc",
    "common.nights": "noce",
    "common.error": "Błąd",
    "common.success": "Sukces",
    "common.saved": "Zapisano",
    "calendar.view_cleaning": "Widok sprzątania",
    "calendar.cleaning_time": "Czas na sprzątanie i konserwację",
    "calendar.guests_short": "os.",
    "calendar.animals_short": "zw.",
    "calendar.occupied": "Zajęte",
    "alert.double_booking": "Wykryto podwójną rezerwację",
    "alert.double_booking_desc": "Istnieją nakładające się rezerwacje na ten sam obiekt. Proszę sprawdź konflikty:",
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const { user } = useAuth();
  const utils = trpc.useUtils();
  const [language, setInternalLanguage] = useState<Language>("EN");

  const updateLanguageMutation = trpc.user.updateLanguage.useMutation({
    onSuccess: () => {
      utils.auth.me.invalidate();
    }
  });

  useEffect(() => {
    if (user?.language) {
      setInternalLanguage(user.language as Language);
    }
  }, [user?.language]);

  const setLanguage = (lang: Language) => {
    setInternalLanguage(lang);
    if (user) {
      updateLanguageMutation.mutate({ language: lang });
    }
  };

  const t = useMemo(() => (key: string) => {
    return translations[language][key] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
