import { z } from "zod";
import { PROPERTIES, CHANNELS, STATUSES, DEPOSIT_STATUSES, CLEANING_STAFF, BOOKING_TYPES } from "./config";

export const bookingFilterSchema = z.object({
  property: z.enum(PROPERTIES).optional(),
  channel: z.enum(CHANNELS).optional(),
  status: z.enum(STATUSES).optional(),
  type: z.enum(BOOKING_TYPES).optional(),
  depositStatus: z.enum(DEPOSIT_STATUSES).optional(),
  checkInFrom: z.coerce.date().optional(),
  checkInTo: z.coerce.date().optional(),
  timeRange: z.enum(["month", "next_month", "3months", "6months", "year", "all"]).optional(),
  limit: z.number().min(1).max(500).default(200),
  offset: z.number().min(0).default(0),
});

export const updateBookingDetailsSchema = z.object({
  id: z.number(),
  property: z.enum(PROPERTIES).optional(),
  type: z.enum(BOOKING_TYPES).optional(),
  checkIn: z.coerce.date().optional(),
  checkOut: z.coerce.date().optional(),
  guestName: z.string().optional(),
  guestCountry: z.string().optional(),
  guestEmail: z.string().optional(),
  guestPhone: z.string().optional(),
  guestCount: z.number().optional(),
  adultsCount: z.number().optional(),
  childrenCount: z.number().optional(),
  animalsCount: z.number().optional(),
  totalPrice: z.string().optional(),
  commission: z.string().optional(),
  hostRevenue: z.string().optional(),
  currency: z.string().optional(),
  amountPaid: z.string().optional(),
  depositAmount: z.string().optional(),
  depositStatus: z.enum(DEPOSIT_STATUSES).optional(),
  channel: z.enum(CHANNELS).optional(),
  status: z.enum(STATUSES).optional(),
  notes: z.string().optional(),
  purpose: z.string().optional(),
  companyName: z.string().optional(),
  nip: z.string().optional(),
  cleaningDate: z.coerce.date().optional(),
  cleaningStaff: z.enum(CLEANING_STAFF).optional(),
});

export const createBookingSchema = z.object({
  property: z.enum(PROPERTIES),
  type: z.enum(BOOKING_TYPES).default("normal"),
  checkIn: z.coerce.date(),
  checkOut: z.coerce.date(),
  guestName: z.string().optional(),
  guestCountry: z.string().optional(),
  guestEmail: z.string().optional(),
  guestPhone: z.string().optional(),
  guestCount: z.number().optional(),
  adultsCount: z.number().optional(),
  childrenCount: z.number().optional(),
  animalsCount: z.number().optional(),
  totalPrice: z.string().optional(),
  commission: z.string().optional(),
  hostRevenue: z.string().optional(),
  currency: z.string().optional(),
  amountPaid: z.string().optional(),
  depositAmount: z.string().optional(),
  depositStatus: z.enum(DEPOSIT_STATUSES).default("pending"),
  channel: z.enum(CHANNELS).default("direct"),
  status: z.enum(STATUSES).default("confirmed"),
  notes: z.string().optional(),
  purpose: z.string().optional(),
  companyName: z.string().optional(),
  nip: z.string().optional(),
});

export const submitBookingSchema = z.object({
  property: z.enum(PROPERTIES),
  checkIn: z.coerce.date(),
  checkOut: z.coerce.date(),
  guestName: z.string(),
  guestEmail: z.string().email(),
  guestPhone: z.string(),
  guestCount: z.number(),
  animalsCount: z.number().default(0),
  notes: z.string().optional(),
  guestCountry: z.string().optional(),
  purpose: z.string().optional(),
  companyName: z.string().optional(),
  nip: z.string().optional(),
});

export const calculatePriceSchema = z.object({
  property: z.enum(PROPERTIES),
  checkIn: z.coerce.date(),
  checkOut: z.coerce.date(),
  guestCount: z.number().optional(),
  animalsCount: z.number().optional(),
});
